blank_issues_enabled: true
contact_links:
  - name: Gitee 帮助中心
    url: https://help.gitee.com/
    about: 提供 Git 使用指南、教程、Gitee.com 平台基本功能使用、介绍和常见问题解答
  - name: DzzOffice 小胡团队
    url: https://gitee.com/xiaohu2024
    about: 其他相关内容，如关于DzzOffice的开发与二次开发，技术交流与分享，教程与问题解答，以及开发手册和文档等方面的内容在团队主页中查看